### ISSUE TITLE
Does not have android functionality.

### ISSUE THREAD

**Issue by malice936** [mebeim/stream-locker#1]
I left a 1 star review on your page and you asked for feedback hut mozilla in all of their infinite wisdom don't allow us to reply back. So to answer your question, it doesn't work period. Even using your example site Openload it does not change to the HTML5 native player for Firefox Android. If you dev a new version for android or add android functionality send me an email malice93652@gmail.com I'll gladly test it for you.

**Comment by mebeim** [comment]
Oh God, I didn't know Mozilla doesn't allow to reply, that's terrible. Thank you very much for reaching out though! 

So from what I understand the extension installs but does not work. That's what I expected sadly, because PC browsers and mobile browsers are very different things. I was not expecting to support Android at all to be honest since I don't even have devices to test on, but if in the future I can manage to solve this I will make sure to let you know. Thank you again for the feedback :slightly_smiling_face:

**Comment by mebeim** [comment]
Removed compatibility *suggestion* for Android from the add-on settings in the Mozilla Add-on store.

**Comment by mebeim** [comment]
Removed compatibility suggestion for Android from the add-on settings in the Mozilla Add-on store.
